# act like vim in copy mode
set-window-option -g mode-keys vi

# increase buffer
set-option -g history-limit 9999

# activate tmux-logging plugin (https://github.com/tmux-plugins/tpm)
set -g @plugin 'tmux-plugins/tmux-logging'

# activate tmux-yank for clipboard copy ()
set -g @plugin 'tmux-plugins/tmux-yank'

# run plugin mgr
run '~/.tmux/plugins/tpm/tpm'

